### PR TITLE
Removed setex and use default set and EX option because setex is depr…

### PR DESCRIPTION
**Pull request by thujikun**
…ecated.

### CODE REVIEW

**Comment by thujikun** [comment]
Amazon ElastiCache redis haven't support 'setex' yet.
So I updated to use default 'set' method and 'EX' option instead.
Moreover I added fineOne method support for cache because it's included in sequelize.

**Comment by rfink** [comment]
Hello and thanks very much for contributing!  I'm also using Amazon ElastiCache, but I haven't encountered an issue with setex.  What engine version are you on?

**Comment by thujikun** [comment]
Sorry for late reply.
My ElastiCache redis version is 2.8.19.

**Comment by roccomuso** [comment]
+1 replace the <code>.setex</code> deprecated method with <code>.set</code>.

**Comment by rfink** [comment]
Do either of you have a link to the deprecation notice?  This is the first I'm hearing of it.

**Comment by roccomuso** [comment]
@rfink the method is not reported on the node_redis documentation.

**Comment by thujikun** [comment]
Here.
http://redis.io/commands/SET

Note: Since the SET command options can replace SETNX, SETEX, PSETEX, it is possible that in future versions of Redis these three commands will be deprecated and finally removed.

**Comment by rfink** [comment]
Thanks.  Did not know that was a possibility.  I'll take a look at this PR and get it merged in, hopefully today.  Thanks again.

**Comment by rfink** [comment]
This is merged and released in 1.4.0.  Thanks!  Glad to find out about the deprecation before it happened.

**Comment by thujikun** [comment]
Thanks! I confirmed it!

**Pull request merged**
